# Generated by Django 4.0.3 on 2022-03-18 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpending',
            name='slip',
        ),
        migrations.AddField(
            model_name='orderpending',
            name='codprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='frombank',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='goodsprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='slip/'),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='shippingprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipcheckedstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipdatetimekeyin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipuploadstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipuploadtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='tobank',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='totallyprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='totalquantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='trackingnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='paymentstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='shippingstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100)),
                ('fullname', models.CharField(default='', max_length=500)),
                ('tel', models.CharField(default='', max_length=100)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('shipping', models.CharField(default='', max_length=100)),
                ('payment', models.CharField(default='', max_length=100)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('shippingstatus', models.BooleanField(blank=True, default=False, null=True)),
                ('paymentstatus', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='slip/')),
                ('transactionid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('frombank', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tobank', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slipamount', models.IntegerField(blank=True, default=0, null=True)),
                ('slipuploadstatus', models.BooleanField(blank=True, default=False, null=True)),
                ('slipuploadtime', models.DateTimeField(blank=True, null=True)),
                ('slipdatetimekeyin', models.CharField(blank=True, max_length=100, null=True)),
                ('slipcheckedstatus', models.BooleanField(blank=True, default=False, null=True)),
                ('goodsprice', models.IntegerField(blank=True, default=0, null=True)),
                ('totalquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('trackingnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('codprice', models.IntegerField(blank=True, default=0, null=True)),
                ('shippingprice', models.IntegerField(blank=True, default=0, null=True)),
                ('totallyprice', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
