# Generated by Django 4.0.3 on 2022-03-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alluser',
        ),
        migrations.DeleteModel(
            name='Userregister',
        ),
    ]
