# Generated by Django 4.0.2 on 2022-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.CharField(blank=b'I00\n', max_length=100, null=b'I00\n'),
        ),
    ]
