# Generated by Django 4.0.3 on 2022-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='slipcheckedstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipdatetimekeyin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipfilelocation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipuploadtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
