# Generated by Django 4.0.3 on 2022-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='note',
            field=models.TextField(),
        ),
    ]
