# Generated by Django 4.0.3 on 2022-03-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderpending_slipcheckedstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='slipuploadtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
