# Generated by Django 4.0.3 on 2022-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_orderpending_address_alter_orderpending_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='transactionid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
