# Generated by Django 4.0.3 on 2022-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_orderpending_slipuploadtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='frombank',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='slipamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='tobank',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
