# Generated by Django 4.0.3 on 2022-03-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orderpending_frombank_orderpending_slipamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpending',
            old_name='slip',
            new_name='image',
        ),
    ]
