# Generated by Django 4.0.2 on 2022-03-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bookid',
            field=models.IntegerField(default=1),
        ),
    ]
