# Generated by Django 4.0.3 on 2022-03-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_orderpending_totalprice_orderpending_totalquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpending',
            name='slipfilelocation',
        ),
    ]
