# Generated by Django 4.0.3 on 2022-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_orderpending_slipfilelocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpending',
            old_name='totalprice',
            new_name='codprice',
        ),
        migrations.AddField(
            model_name='orderpending',
            name='goodsprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='shippingprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='totallyprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
