# Generated by Django 4.0.2 on 2022-03-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_cart_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bookid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(),
        ),
    ]
