# Generated by Django 4.0.3 on 2022-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_totalprice_orderpending_codprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='slipuploadstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
