# Generated by Django 4.0.3 on 2022-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_orderpending_slipuploadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='paymentstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='shippingstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
