# Generated by Django 4.0.3 on 2022-03-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_profile_cartquan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sumtotal',
            field=models.IntegerField(default=0),
        ),
    ]
